// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjT5VTtRQh0jCaeRtX6KmJkd-Ls-a24c4',
    appId: '1:335735069521:web:f16bf1dbba1b44510b9170',
    messagingSenderId: '335735069521',
    projectId: 'logitrack-117b0',
    authDomain: 'logitrack-117b0.firebaseapp.com',
    storageBucket: 'logitrack-117b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpznsbJ8ScYHEA23x2uGyMzKQhgucMMY',
    appId: '1:335735069521:android:885c796252e46ce20b9170',
    messagingSenderId: '335735069521',
    projectId: 'logitrack-117b0',
    storageBucket: 'logitrack-117b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaxbQcDRZ3QJyUrGJVMKimJrUlG3fxdaE',
    appId: '1:335735069521:ios:f9c5065c8b1631b30b9170',
    messagingSenderId: '335735069521',
    projectId: 'logitrack-117b0',
    storageBucket: 'logitrack-117b0.firebasestorage.app',
    iosClientId: '335735069521-525bvv7657n3n7r1k62iuei5qga7gni2.apps.googleusercontent.com',
    iosBundleId: 'com.example.logitrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaxbQcDRZ3QJyUrGJVMKimJrUlG3fxdaE',
    appId: '1:335735069521:ios:f9c5065c8b1631b30b9170',
    messagingSenderId: '335735069521',
    projectId: 'logitrack-117b0',
    storageBucket: 'logitrack-117b0.firebasestorage.app',
    iosClientId: '335735069521-525bvv7657n3n7r1k62iuei5qga7gni2.apps.googleusercontent.com',
    iosBundleId: 'com.example.logitrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjT5VTtRQh0jCaeRtX6KmJkd-Ls-a24c4',
    appId: '1:335735069521:web:480b104bde728f0f0b9170',
    messagingSenderId: '335735069521',
    projectId: 'logitrack-117b0',
    authDomain: 'logitrack-117b0.firebaseapp.com',
    storageBucket: 'logitrack-117b0.firebasestorage.app',
  );
}
